# Generated by Django 3.2.19 on 2023-06-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20230629_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpost',
            name='username',
            field=models.CharField(max_length=32, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='likescomment',
            name='username',
            field=models.CharField(max_length=32, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='likespost',
            name='username',
            field=models.CharField(max_length=32, verbose_name='Текст'),
        ),
    ]
