# Generated by Django 3.2.19 on 2023-06-29 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20230629_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='Логин')),
            ],
        ),
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='Логин')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_post', to='blog.post')),
            ],
        ),
        migrations.RemoveField(
            model_name='likespost',
            name='post',
        ),
        migrations.AlterField(
            model_name='commentpost',
            name='username',
            field=models.CharField(max_length=32, verbose_name='Логин'),
        ),
        migrations.DeleteModel(
            name='LikesComment',
        ),
        migrations.DeleteModel(
            name='LikesPost',
        ),
        migrations.AddField(
            model_name='likecomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_comment', to='blog.commentpost'),
        ),
    ]
